config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about'=>'homes#about' , as:'about'
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:show, :index , :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment ,presence: true 
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true, presence: true , length: { minimum: 2, maximum:20 }
  validates :introduction, length: { maximum:50 }
end

 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!,except: [:top , :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    books_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
    
  end
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def index
    @book = Book.new
    @user=current_user
    @books = Book.all
    
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user=current_user
    if @book.save
      flash[:success]="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @uesr=current_user
      @books=Book.all
      render 'index'
    end
  end

  def show
    @book = Book.find(params[:id])
    @user= @book.user
    @book_comment = BookComment.new
    
  end

  def edit
    @book=Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully"
      redirect_to book_path(@book.id)
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
    #@user=@book.user
    book.destroy
    redirect_to books_path

  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def index
    books=Book.all
  end
  
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location:root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location:root_path)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users=User.all
    @books=@user.books
    
  end
  

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'You have updated user successfully.'  
      redirect_to user_path(@user.id)
    else
      render:edit
    end    
  end

  def index
    @user=current_user
    @users=User.all
    @books=Book.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, size:"100x100" , format: 'jpeg', fallback: "no_image.jpeg", class: "attachment user profile_image fallback" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>

  </tbody>
</table>
<div class="row mt-5">
  <%= link_to "" , edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog "  %>
</div>


<h2 class="mt-3">New book</h2>
  <%= form_with model:Book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/_favorite.html.erb
<td>  
  <% if book.favorited_by?(current_user) %>
  
    <%= link_to book_favorites_path(book), method: :delete do %>
      <i class="fas fa-heart" ><%= book.favorites.count  %></i>
    <% end %>
  
  <% else %>
  
    <%= link_to book_favorites_path(book), method: :post do %>
      <i class="far fa-heart"><%= book.favorites.count %></i> 
    <% end %>
  
  <% end %>
</td>

app/views/books/edit.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= form_with model:@book, local: true do |f| %>
          <div class="form-group">
            <%= f.label:title , "Title" %><br/>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <%= f.label:body , "Opinion" %><br/>
            <%= f.text_field :body %>
          </div>
          <div class="form-group">
            <%= f.submit 'Update Book' , calss: "btn btn-success" %>
          </div>
          <%= link_to "Show" , book_path(@book) %>
          |
          <%= link_to "Back" , books_path %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p></p>
  <div class="container">
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
        <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/book', user: @user , book: @book %>
      </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
          
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%=link_to user_path(book.user) do %>
                      <%= attachment_image_tag book.user, :profile_image,size:"50x50", format: 'jpeg', fallback: "no_image.jpeg", class: "attachment user profile_image fallback" %>
                    <% end %>
                  </td>
                  <td><%=link_to book.title , book_path(book.id) %></td>
                  <td><%=book.body %></td>
                  
                  <%= render 'books/favorite' ,book:book %>
                  
                  <td>コメント数：<%=book.book_comments.count %></td>
                </tr>
              <% end %>

            </tbody>
          </table>
        </div>
      </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">

      <div class="col-md-3">
        <%= render 'books/book', user: @user , book: @book %>
      </div>



        <div class="col-md-8 offset-md-1">
          <h2>Book detail</h2>
          <table class="table">
            <tbody>

              <tr>
                <td>
                  <%=link_to user_path(@user) do %>
                    <%= attachment_image_tag @user, :profile_image, size:"50x50", format: 'jpeg', fallback: "no_image.jpeg", class: "attachment user profile_image fallback" %><br/>
                    <%= @user.name %>
                  <% end %>
                </td>
                <td><%=link_to @book.title , book_path(@book) %></td>
                <td><%=@book.body %></td>
                <%= render 'books/favorite' , book:@book %>
                <td>コメント数：<%=@book.book_comments.count %></td>

                <% if @user.id == current_user.id %>
                  <td><%= link_to "Edit" , edit_book_path(@book.id) , class:"btn btn-sm btn-success"  %></td>
                  <td><%= link_to "Destroy", book_path(@book), method: :delete , class:"btn btn-sm btn-danger" ,"data-confirm" => "本当に削除しますか？"  %></td>
                <% end %>

              </tr>

            </tbody>
          </table>

          <table>
            <tbody>
              <tr>
                  <% @book.book_comments.each do |book_comment| %>
                    <tr>
                      <td>
                        <%=link_to user_path(book_comment.user) do %>
                          <%= attachment_image_tag book_comment.user, :profile_image, size:"50x50", format: 'jpeg', fallback: "no_image.jpeg", class: "attachment user profile_image fallback" %><br/>
                          <%= book_comment.user.name %>
                        <% end %>
                      </td>
                      
                      
                      <td>
                        <%= book_comment.comment %>
                      </td>
                      <% if book_comment.user == current_user %>
                        <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete , class:"btn btn-sm btn-danger"   %></td>
                      <% end %>
                    </tr>

                  <% end %>
              </tr>
            </tbody>
          </table>

          <div class="new-comment">
          <%= form_with(model: [@book, BookComment.new ] , local: true) do |f| %>
            <%= f.text_area :comment, :size=>"90x5" %><br/>
            <%= f.submit "送信" %>
          <% end %>
          </div>

        </div>
      </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
      </div>
      <div class="btn-wrapper col-7 mx-auto">
        <div>
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 "%>
        </div>
        <div>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block "%>
        </div>
        
      </div>
    </div>
  </div>
</mian>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value) %>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand " href="/"><span>Bookers</span></a>

            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to 'Home', user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "Users" , users_path, class: "fas fa-users nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "Books" , books_path, class: "fas fa-book-open nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "logout" , destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
                </li>
              <% else %>
                <li>
                  <%= link_to"Home" , root_path , class: "fas fa-home nav-link text-light"%>
                </li>
                <li>
                  <%= link_to"About" , about_path, class: "fas fa-link nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
                </li>
                <li>
                  <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
                </li>
              <% end %>
            </ul>

        </div>
      </nav>
    </header>
    
      <%= render 'layouts/notifications' %>
  
 
    <%= yield %>

    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		    <p>CopyRight Infratop.inc</p>
    	    </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<main>
  <p></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <h2>User info</h2>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <%= f.label:name,"Name" %><br/>
            <%=  f.text_field :name %>
          </div>
          
          <div class="form-group">
            <%= f.label:profile_image ,"Image" %>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file user_image"%>
          </div>
    
          <div class="form-group">
            <%=f.label:introduction,"Introduction" %><br/>
            <%=  f.text_area :introduction %>
          </div>
    
          <div class="form-group">
            <%= f.submit 'Update User',class:"btn btn-secondary" %>
          </div>
        <% end %>    
      </div>
    </div>
  </div>
</main>

    
    

app/views/users/index.html.erb
<main>
  <p></p>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">
        <%= render 'books/book', user: @user , book: @book  %>
      </div>

        <div class="col-md-8 offset-md-1">
          <h2>Users</h2>
          <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <%=link_to user_path(@user) do %>
                      <%= attachment_image_tag user, :profile_image, size:"50x50" , format: 'jpeg', fallback: "no_image.jpeg", class: "attachment user profile_image fallback" %>
                    <% end %>
                  </td>
                  <td><%= user.name %></td>
                  <td><%=link_to "Show" , user_path(user) %></td>
                </tr>

              <% end %>

            </tbody>
          </table>
        </div>
      </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p></p>
  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">
        <%= render 'books/book', user: @user , book: @book %>
      </div>

        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td>
                    <%=link_to user_path(@user) do %>
                      <%= attachment_image_tag @user, :profile_image,size:"50x50" , format: 'jpeg', fallback: "no_image.jpeg", class: "attachment user profile_image fallback" %>
                    <% end %>
                  </td>
                  <td><%= link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body  %></td>
                  <%=render 'books/favorite', book:book %>
                  <td>コメント数：<%=book.book_comments.count %></td>

                </tr>

              <% end %>

            </tbody>
          </table>
        </div>
      </div>
  </div>
</main>